name: Integration
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install clippy and rustfmt
      run: |
        rustup component add clippy
        rustup component add rustfmt
    # Checking normal
    - name: Run tests
      run: |
        cargo test
        cargo clippy
    # Checking fmt
    - name: Rustfmt
      run: cargo fmt -- --check

